name: saude_indigena_app
description: "Aplicativo para gestão de saúde indígena no campo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacotes que você já usa ou vai usar
  shared_preferences: ^2.2.2
  
  # PACOTES DO BANCO DE DADOS (Adicione estas linhas abaixo)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # GERADORES DE CÓDIGO DO BANCO (Adicione estas linhas abaixo)
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true