name: saude_indigena_app
description: "Aplicativo para gestão de saúde indígena no campo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Conectividade e Armazenamento Local
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  # FIREBASE (Sincronização em Nuvem e Autenticação)
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # Banco de Dados Local (Drift/SQLite)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Geradores de Código do Banco
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true