// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnvwpDqMjL6WTrlnKy6BaC5IEdv46QopE',
    appId: '1:334446623834:web:6c4d42b42d9d58a80d2c63',
    messagingSenderId: '334446623834',
    projectId: 'saude-indigena-app',
    authDomain: 'saude-indigena-app.firebaseapp.com',
    storageBucket: 'saude-indigena-app.firebasestorage.app',
    measurementId: 'G-SDYTJMF8LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnsCiC2BkhD8z7Ru1O1fsqFwxUpAP-O9M',
    appId: '1:334446623834:android:c80c6c106fe8c0be0d2c63',
    messagingSenderId: '334446623834',
    projectId: 'saude-indigena-app',
    storageBucket: 'saude-indigena-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-nys4ogse4VNcGoHsm9saqWeiRARvE0',
    appId: '1:334446623834:ios:5577362ee6eb49860d2c63',
    messagingSenderId: '334446623834',
    projectId: 'saude-indigena-app',
    storageBucket: 'saude-indigena-app.firebasestorage.app',
    iosBundleId: 'com.example.saudeIndigenaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-nys4ogse4VNcGoHsm9saqWeiRARvE0',
    appId: '1:334446623834:ios:5577362ee6eb49860d2c63',
    messagingSenderId: '334446623834',
    projectId: 'saude-indigena-app',
    storageBucket: 'saude-indigena-app.firebasestorage.app',
    iosBundleId: 'com.example.saudeIndigenaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnvwpDqMjL6WTrlnKy6BaC5IEdv46QopE',
    appId: '1:334446623834:web:bc83085b1a713e5b0d2c63',
    messagingSenderId: '334446623834',
    projectId: 'saude-indigena-app',
    authDomain: 'saude-indigena-app.firebaseapp.com',
    storageBucket: 'saude-indigena-app.firebasestorage.app',
    measurementId: 'G-4YG3HGBDR2',
  );
}
